/**
 * @file
 * @brief       Private parameters for the API013RemoteFunction module.
 *
 * @details     Refer to the C source file for more detailed information.
 *
 * @copyright   Copyright 2016-2017 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

#ifndef API013REMOTEFUNCTION_PRV_H_
#define API013REMOTEFUNCTION_PRV_H_


// --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --

// -- Other Modules --
#include "RemoteFunctionExtraction.h"
#include "RemoteFunctionInterface.h"
#include "SRMC_defs.h"


//=====================================================================================================================
//  --- Private Properties --------------------------------------------------------------------------------------------
//=====================================================================================================================


// -- Private Constant Declarations --

//! The maximum number of handlers that will process events generated by the API013_SERVER_FEATURE.
#define API013_MAX_CALLBACK_HANDLERS 2

//! The maximum number of data elements that can be published in the API013_FBK_PUBLISH_CALCULATED_RESULTS message.
#define API013_MAX_PUBLISHED_DATA 16

//! The maximum number of data elements that can be stored in memory at any point in time.
#define API013_MAX_STORED_DATA 16

//! The number of milliseconds between calls to the API013MotionCtrl__Handler() function.
#define API013_MS_PER_BACKGROUND_CALL 25


// -- Private Type Declarations --


// -- Private Flash-Based Constant Definitions --

#if (API013_CLIENT_FEATURE == ENABLED)
    //! An array of remote functions used in API013 Communication.
    //! This list has a one-to-one correspondence with the #API013_CLIENT_FUNCTION_INDEX_TYPE.
    //! The first parameter of each entry is the communication node of the server.
    //! The second parameter of each entry is the 0-based index of the remote function on the server.
    static const API013_FUNCTION_CONFIG_TYPE API013_CLIENT_FUNCTIONS[] =
    {
    //  {Communication_Node,    Server_Function_Index}
        {0,                     0}
    };
#endif      // #if (API013_CLIENT_FEATURE == ENABLED)

#if (API013_SERVER_FEATURE == ENABLED)
    //! The list of configuration structures for each of the Background Analyses.

    #if(WINDY_STRIP_BOARD == 1)
    static const REMOTE_FUNCTION_HOOK_TYPE API013_SERVER_FUNCTIONS[] =
    {
    //  {Background Function,                 	 Command Function,                    	 Get Data Function,                  	Get Status Function}
        {RemoteFunctionExtraction__Background,   RemoteFunctionExtraction__DoCommand,    REMOTE_FUNCTION_GET_DATA_NULL,     RemoteFunctionExtraction__GetStatus   },
    //	 {REMOTE_FUNCTION_BACKGROUND_NULL,   REMOTE_FUNCTION_DO_CONTROL_NULL,    REMOTE_FUNCTION_GET_DATA_NULL,     REMOTE_FUNCTION_GET_STATUS_NULL   }
    };
    #elif(WINDY_INTERNATION_BOARD == 1)
	#include "RemoteFunctionChildSafety.h"
	
    static const REMOTE_FUNCTION_HOOK_TYPE API013_SERVER_FUNCTIONS[] =
    {
    //  {Background Function,                    Command Function,                       Get Data Function,                     Get Status Function}
        {RemoteFunctionExtraction__Background,   RemoteFunctionExtraction__DoCommand,    REMOTE_FUNCTION_GET_DATA_NULL,     RemoteFunctionExtraction__GetStatus   },
        {RemoteFunctionChildSafety__Background,  RemoteFunctionChildSafety__DoCommand,   REMOTE_FUNCTION_GET_DATA_NULL,     RemoteFunctionChildSafety__GetStatus   }
    };
    #endif

#endif      // #if (API013_SERVER_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Private Methods -----------------------------------------------------------------------------------------------
//=====================================================================================================================


#endif      /* API013REMOTEFUNCTION_PRV_H_ */
