/**
 * @file
 * @brief       Public parameters for the API221MotionCtrl module.
 *
 * @details     Refer to the C source file for more detailed information.
 *
 * @copyright   Copyright 2016-2017 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

#ifndef API221MOTIONCTRL_PRM_H_
#define API221MOTIONCTRL_PRM_H_


//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --

// -- Other Modules --


//=====================================================================================================================
//  --- Public Properties ---------------------------------------------------------------------------------------------
//=====================================================================================================================


// -- Public Constant Declarations --


// -- Public Enumerated Constant Declarations --

//! Define API221_PLATFORM_SPECIFIC_EVENT_LIST to create events that are generated by the
//! platform-specific motion behaviors. These values will be added to the API221_MOTOR_EVENT_TYPE.
#define API221_PLATFORM_SPECIFIC_EVENT_LIST \
    API221_EVENT_PULSE_RUNNING = 7          \


// -- Public Type Declarations --

#if (API221_CLIENT_FEATURE == ENABLED)
    //! An enumerated list of all motors in the appliance system.
    //! The last enum, API221_CLIENT_MOTOR_COUNT, specifies the number of system motors.
    //! This list has a one-to-one correspondence with the API221_MOTOR_IDS[] array.
    typedef enum API221_CLIENT_MOTOR_INDEX_ENUM
    {
        API221_MOTOR_NAME_1
    } API221_CLIENT_MOTOR_INDEX_TYPE;
#else
    typedef uint8 API221_CLIENT_MOTOR_INDEX_TYPE;
#endif      // #if (API221_CLIENT_FEATURE == ENABLED)


//=====================================================================================================================
//  --- Public Methods ------------------------------------------------------------------------------------------------
//=====================================================================================================================



#endif      // API221MOTIONCTRL_PRM_H_
