/**
 * @file
 * @brief       One-line description of the module.
 *
 * @details     Detailed description of the module.
 *
 * @copyright   Copyright 2016 Whirlpool Corporation.  All rights reserved - CONFIDENTIAL.
 */

//  --- Include Files -------------------------------------------------------------------------------------------------

// -- This Module --
#include "C_Extensions.h"
#include "MotorActivity.h"

// -- Other Modules --
#include "Log.h"
#include "Motion.h"
#include "Utilities.h"


//  --- Private Properties --------------------------------------------------------------------------------------------

// -- Private Constant Declarations --

//! The name of this module for use by the Log module.
#define MODULE_NAME MODULE_MOTOR_ACTIVITY

//! Macro to convert a pulse time (high and low bytes) to milliseconds.
#define GET_MS(hi,lo) (100 * COMBINE_BYTES((hi),(lo)))


// -- Private Type Declarations --

//! A list of log message IDs that are generated by this module.
typedef enum MODULE_MOTOR_ACTIVITY_LOG_MESSAGE_ID_ENUM
{
    PULSE_TIME_OFF_MULTIPLIER_INVALID,              //!< data: the invalid time prescalar multiplier index
    PULSE_TIME_ON_MULTIPLIER_INVALID,               //!< data: the invalid time prescalar multiplier index
    UNSUPPORTED_MOTOR_ACTIVITY
} MODULE_MOTOR_ACTIVITY_LOG_MESSAGE_ID_TYPE;


// -- Private Variable Definitions --


//  --- Private Function Prototypes -----------------------------------------------------------------------------------


//=====================================================================================================================
//  --- Public Methods ------------------------------------------------------------------------------------------------
//=====================================================================================================================


//---------------------------------------------------------------------------------------------------------------------
/**
 * Stop all motor activity.
 * @param deceleration = Deceleration for ramping to 0 rpm.
 * @param requestor = Module that is requesting the run for priority purposes.
 */
BOOL_TYPE MotorActivity__Stop(uint16 deceleration, MOTION_REQUESTOR_TYPE requestor)
{
    MOTION_PROFILE_TYPE profile;

    profile.Stop.Drum_Deceleration = deceleration;
    Motion__Activity(MOTION_ACTIVITY_STOP, profile, requestor);
    Motion__Release(requestor);

    return TRUE;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Run the motor as specified.
 * @param velocity = Velocity to run the motor.
 * @param acceleration = Acceleration for ramping to the new speed.
 * @param requestor = Module that is requesting the run for priority purposes.
 */
BOOL_TYPE MotorActivity__Run(sint16 velocity, uint16 acceleration, MOTION_REQUESTOR_TYPE requestor)
{
    MOTION_PROFILE_TYPE profile;
    profile.Spin.Target_Drum_Velocity = (MOTION_DRUM_VELOCITY_TYPE)velocity;
    profile.Spin.Drum_Acceleration = (MOTION_DRUM_ACCELERATION_TYPE)acceleration;
    Motion__Activity(MOTION_ACTIVITY_SPIN, profile, requestor);

    return TRUE;
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Request a new motor activity.
 * @param activity = The API039_ACTIVITY_TYPE value that specifies the requested motor activity.
 * @param parameters = The address of parameters with configuration information for the requested motor activity.
 * @param size = The number of bytes in the configuration information for the requested motor activity.
 * @return TRUE if the activity was accepted. FALSE if the activity was not requested.
 */
BOOL_TYPE MotorActivity__Set(uint8* parameters, uint8 size, MOTION_REQUESTOR_TYPE requestor)
{
    MOTION_PROFILE_TYPE profile;
    BOOL_TYPE activity_accepted = FALSE;
    MOTOR_ACTIVITY_COMMAND_TYPE activity = (MOTOR_ACTIVITY_COMMAND_TYPE)parameters[0];
    switch ( activity )
    {
        case MOTOR_ACTIVITY_STOP:
            // TODO: Remove when API039 is removed.
            profile.Stop.Drum_Deceleration = Utilities__ConvertArrayTo16bits(&parameters[1]);
            Motion__Activity(MOTION_ACTIVITY_STOP, profile, requestor);
            activity_accepted = TRUE;
            break;

        case MOTOR_ACTIVITY_RUN:
            // TODO: Remove when API039 is removed.
            if (size >= 4)
            {
                profile.Spin.Target_Drum_Velocity = Utilities__ConvertArrayTo16bits(&parameters[1]);
                profile.Spin.Drum_Acceleration = Utilities__ConvertArrayTo16bits(&parameters[3]);
                Motion__Activity(MOTION_ACTIVITY_SPIN, profile, requestor);
                activity_accepted = TRUE;
            }
            break;

        case MOTOR_ACTIVITY_PULSE:
            if (size >= 8)
            {
                profile.Pulse.Behavior = (PULSE_BEHAVIOR_TYPE)(parameters[1]);
                profile.Pulse.Spin_Drum_Profile.Target_Drum_Velocity = (sint16)(sint8)(parameters[2]);
                profile.Pulse.Spin_Drum_Profile.Drum_Acceleration = 100 * (uint16)parameters[3];
                profile.Pulse.Time_On = GET_MS(parameters[5], parameters[4]);
                profile.Pulse.Time_Off = GET_MS(parameters[7], parameters[6]);
                Motion__Activity(MOTION_ACTIVITY_PULSE, profile, requestor);
                activity_accepted = TRUE;
            }
            break;

        default:
            LOG_ADD_EXCEPTION(UNSUPPORTED_MOTOR_ACTIVITY, activity);
            activity_accepted = FALSE;
            break;
    }

    return ( activity_accepted );
}


//---------------------------------------------------------------------------------------------------------------------
/**
 * Request the status of the current motor activity.
 * @param buffer = Pointer to the address of the motor activity status information. This function sets the address.
 * @param size = Pointer to the number of bytes in the motor activity status information. This function sets the size.
 */
void MotorActivity__GetStatus(uint8** buffer, uint8* size)
{
    static MOTION_STATUS_TYPE status;

    status = Motion__GetStatus();
    *buffer = (uint8*)&status;                      //lint !e928 Suppress Info: cast from pointer to pointer [MISRA 2004 Rule 11.4]
    *size = sizeof(MOTION_STATUS_TYPE);
}


//=====================================================================================================================
//  --- Private Methods -----------------------------------------------------------------------------------------------
//=====================================================================================================================
